kind: Service
apiVersion: v1
metadata:
  name: simple-web-app
spec:
  selector:
    app: simple-web-app
  ports:
    - protocol: TCP
      port: 80 # Default port for image
      targetPort: 5000
  type: LoadBalancer

